# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.13"
  gem "rspec_junit_formatter", "~> 0.6"
  gem "rubocop", "~> 1.81"
  gem "rubocop-rspec", "~> 3.7"
  gem "webmock", "~> 3.25"
end
